# Generated by Django 5.2.4 on 2025-07-10 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('model_type', models.CharField(max_length=50)),
                ('model_file', models.FileField(upload_to='ml_models/')),
                ('is_active', models.BooleanField(default=True)),
                ('accuracy', models.FloatField(null=True)),
                ('precision', models.FloatField(null=True)),
                ('recall', models.FloatField(null=True)),
                ('f1_score', models.FloatField(null=True)),
                ('trained_on', models.DateTimeField()),
                ('training_data_size', models.PositiveIntegerField()),
                ('last_evaluation', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('highlight_score', models.FloatField()),
                ('chat_intensity', models.FloatField()),
                ('viewer_spike', models.FloatField()),
                ('event_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('thumbnail_timestamp', models.FloatField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
            ],
        ),
        migrations.CreateModel(
            name='StreamerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('overall_sentiment_score', models.FloatField(default=0.0)),
                ('sentiment_breakdown', models.JSONField(default=dict)),
                ('content_category_predictions', models.JSONField(default=dict)),
                ('content_tags', models.JSONField(default=list)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('engagement_factors', models.JSONField(default=dict)),
                ('growth_rate', models.FloatField(null=True)),
                ('growth_factors', models.JSONField(default=dict)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Streamer Analytics',
            },
        ),
        migrations.CreateModel(
            name='StreamerInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('best_streaming_times', models.JSONField(default=list)),
                ('optimal_stream_duration', models.JSONField(default=dict)),
                ('content_recommendations', models.JSONField(default=list)),
                ('audience_demographics', models.JSONField(default=dict)),
                ('audience_interests', models.JSONField(default=list)),
                ('audience_engagement_patterns', models.JSONField(default=dict)),
                ('growth_opportunities', models.JSONField(default=list)),
                ('improvement_areas', models.JSONField(default=list)),
                ('competitor_analysis', models.JSONField(default=dict)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamContentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('inappropriate_content_score', models.FloatField()),
                ('violence_score', models.FloatField()),
                ('adult_content_score', models.FloatField()),
                ('hate_speech_score', models.FloatField()),
                ('noise_level', models.FloatField()),
                ('speech_clarity', models.FloatField()),
                ('music_detected', models.BooleanField()),
                ('brightness_score', models.FloatField()),
                ('motion_score', models.FloatField()),
                ('scene_changes', models.PositiveIntegerField()),
                ('object_detection_results', models.JSONField(default=list)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
            ],
            options={
                'indexes': [models.Index(fields=['stream', 'timestamp'], name='analytics_s_stream__a4cddd_idx')],
            },
        ),
    ]
