# Generated by Django 5.2.4 on 2025-07-10 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(max_length=20)),
                ('rule_data', models.JSONField()),
                ('action', models.CharField(max_length=20)),
                ('action_duration', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ml_assisted', models.BooleanField(default=False)),
                ('sensitivity', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('can_moderate', models.BooleanField(default=False)),
                ('can_respond', models.BooleanField(default=True)),
                ('can_schedule_messages', models.BooleanField(default=True)),
                ('uses_ml', models.BooleanField(default=False)),
                ('personality_type', models.CharField(default='friendly', max_length=50)),
                ('learning_enabled', models.BooleanField(default=False)),
                ('custom_responses', models.JSONField(default=dict)),
                ('scheduled_messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('streamer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChatCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50)),
                ('response', models.TextField()),
                ('cooldown', models.PositiveIntegerField(default=0)),
                ('user_level', models.CharField(default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(null=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('streamer', 'command')},
            },
        ),
        migrations.CreateModel(
            name='ChatEmote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='emotes/')),
                ('is_animated', models.BooleanField(default=False)),
                ('tier_required', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('streamer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('is_moderated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sentiment_score', models.FloatField(null=True)),
                ('toxicity_score', models.FloatField(null=True)),
                ('language_detected', models.CharField(max_length=10, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['stream', 'created_at'], name='chat_chatme_stream__759c89_idx'), models.Index(fields=['user', 'created_at'], name='chat_chatme_user_id_bd720b_idx')],
            },
        ),
    ]
