# Generated by Django 5.2.4 on 2025-07-10 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(null=True)),
                ('related_tags', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DurationField()),
                ('end_time', models.DurationField()),
                ('duration', models.DurationField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('highlight_score', models.FloatField()),
                ('auto_generated', models.BooleanField(default=False)),
                ('content_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-highlight_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='playlist_thumbnails/')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_categorized', models.BooleanField(default=False)),
                ('content_category', models.CharField(blank=True, max_length=50)),
                ('suggested_videos', models.JSONField(default=list)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('video_url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='vod_thumbnails/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_subscribers_only', models.BooleanField(default=False)),
                ('chapters', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('content_tags', models.JSONField(default=list)),
                ('category_predictions', models.JSONField(default=dict)),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.highlight')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.playlist')),
                ('vod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.vod')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='highlight',
            name='vod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.vod'),
        ),
        migrations.CreateModel(
            name='ContentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_summary', models.TextField()),
                ('key_moments', models.JSONField(default=list)),
                ('topics_discussed', models.JSONField(default=list)),
                ('video_quality', models.CharField(max_length=20)),
                ('frame_rate', models.PositiveIntegerField()),
                ('audio_quality', models.CharField(max_length=20)),
                ('file_size', models.PositiveBigIntegerField()),
                ('engagement_prediction', models.FloatField()),
                ('recommended_thumbnail_time', models.DurationField(null=True)),
                ('auto_chapters', models.JSONField(default=list)),
                ('scene_analysis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlight', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.highlight')),
                ('vod', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.vod')),
            ],
        ),
        migrations.AddIndex(
            model_name='vod',
            index=models.Index(fields=['streamer', 'published_at'], name='content_vod_streame_34fa78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('playlist', 'order')},
        ),
    ]
