# Generated by Django 5.2.4 on 2025-07-10 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('thumbnail', models.ImageField(blank=True, upload_to='stream_thumbnails/')),
                ('is_live', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('peak_viewers', models.PositiveIntegerField(default=0)),
                ('stream_quality', models.CharField(default='auto', max_length=20)),
                ('is_mature_content', models.BooleanField(default=False)),
                ('chat_enabled', models.BooleanField(default=True)),
                ('subscriber_only_chat', models.BooleanField(default=False)),
                ('followers_only_chat', models.BooleanField(default=False)),
                ('slow_mode', models.PositiveIntegerField(default=0)),
                ('sentiment_score', models.FloatField(null=True)),
                ('content_safety_score', models.FloatField(null=True)),
                ('highlight_timestamps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('video_url', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='clip_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_highlight', models.BooleanField(default=False)),
                ('highlight_score', models.FloatField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
            ],
        ),
        migrations.CreateModel(
            name='StreamKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('streamer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('viewer_count', models.PositiveIntegerField()),
                ('chat_message_count', models.PositiveIntegerField()),
                ('bitrate', models.PositiveIntegerField()),
                ('fps', models.FloatField()),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('dropped_frames', models.PositiveIntegerField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
            ],
            options={
                'indexes': [models.Index(fields=['stream', 'timestamp'], name='streams_str_stream__c69869_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreamQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=20)),
                ('bitrate', models.PositiveIntegerField()),
                ('resolution', models.CharField(max_length=20)),
                ('fps', models.PositiveIntegerField(default=30)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
            ],
            options={
                'unique_together': {('stream', 'quality')},
            },
        ),
    ]
