# Generated by Django 5.2.4 on 2025-07-10 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartNotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('notification_types', models.JSONField()),
                ('user_segments', models.JSONField(default=list)),
                ('ml_model', models.CharField(max_length=50)),
                ('minimum_relevance_score', models.FloatField(default=0.5)),
                ('engagement_threshold', models.FloatField(default=0.3)),
                ('conditions', models.JSONField()),
                ('actions', models.JSONField()),
                ('success_rate', models.FloatField(default=0.0)),
                ('total_processed', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority_score', models.FloatField(default=0.0)),
                ('user_engagement_prediction', models.FloatField(null=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='streams.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField()),
                ('read_at', models.DateTimeField(null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(null=True)),
                ('time_to_read', models.DurationField(null=True)),
                ('time_to_click', models.DurationField(null=True)),
                ('user_action_taken', models.BooleanField(default=False)),
                ('device_type', models.CharField(max_length=50, null=True)),
                ('platform', models.CharField(max_length=50, null=True)),
                ('engagement_score', models.FloatField(null=True)),
                ('effectiveness_score', models.FloatField(null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_streams', models.BooleanField(default=True)),
                ('stream_reminders', models.BooleanField(default=True)),
                ('vod_uploads', models.BooleanField(default=True)),
                ('new_followers', models.BooleanField(default=True)),
                ('mentions', models.BooleanField(default=True)),
                ('chat_highlights', models.BooleanField(default=True)),
                ('donations', models.BooleanField(default=True)),
                ('subscriptions', models.BooleanField(default=True)),
                ('achievements', models.BooleanField(default=True)),
                ('streamer_announcements', models.BooleanField(default=True)),
                ('schedule_changes', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('notification_schedule', models.JSONField(default=dict)),
                ('smart_notifications', models.BooleanField(default=True)),
                ('priority_threshold', models.FloatField(default=0.5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('schedule_type', models.CharField(max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('recurrence_pattern', models.JSONField(blank=True, null=True)),
                ('last_sent', models.DateTimeField(null=True)),
                ('smart_targeting', models.BooleanField(default=False)),
                ('engagement_optimization', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmetrics',
            index=models.Index(fields=['notification', 'delivered_at'], name='notificatio_notific_79cbf3_idx'),
        ),
    ]
